backend:
  name: github
  repo: owenauch/the-movie-harris

media_folder: content/assets
public_folder: content/reviews

collections:
  - name: review
    label: Review
    folder: content/reviews
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: rating, label: Rating, widget: number, valueType: "float" }
      - { name: body, label: Body, widget: markdown }